logger:
  default: error
  logs:
    homeassistant.core: warning
    homeassistant.components.mqtt: warning
    homeassistant.components.life360: fatal
    # pynetgear: debug
    # homeassistant.components.sensor.miflora: debug
    # miflora.miflora_poller: debug