# Depends of the History conponent - https://www.home-assistant.io/components/recorder/
recorder:
  purge_keep_days: 5
  db_url: mysql://hass:hass@core-mariadb/homeassistant?charset=utf8
  # include:
  #   domains:
  #     - sensor
  #     - switch
  #     - media_player
  #     - cover
  #     - light
  #     - binary_sensor
  #     - vacuum
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.time