platform: miflora
mac: !secret entitie_miflora_green_ficus_bonsai
name: Bonsai Ficus
force_update: true
median: 3
monitored_conditions:
  - moisture
  - light
  - temperature
  - conductivity
  - battery