platform: miflora
mac: !secret entitie_miflora_green_little_bonsai
name: Bonsai Japanese
force_update: true
median: 3
monitored_conditions:
  - moisture
  - light
  - temperature
  - conductivity
  - battery